["Library/texmf/tex/latex"]
    type = "archive"
    url = "https://github.com/tud-cd/tud-cd/archive/master.tar.gz"
    refreshPeriod = "168h"
    stripComponents = 3
    exact = true
    include = ["*/tex/latex/tud-beamerstyle/**", "*/tex/latex/tudmathposter/**"]

["bin/paper_store_sparse.sh"]
    type = "file"
    executable = true
    url = "https://raw.githubusercontent.com/nurupo/paper-store/master/paper_store_sparse.sh"
    refreshPeriod = "168h"

[".config/csl/styles/apa.csl"]
    type = "file"
    url = "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"
    refreshPeriod = "168h"

[".config/csl/locales/locales-de-DE.xml"]
    type = "file"
    url = "https://raw.githubusercontent.com/citation-style-language/locales/master/locales-de-DE.xml"
    refreshPeriod = "168h"

[".config/csl/locales/locales-en-US.xml"]
    type = "file"
    url = "https://raw.githubusercontent.com/citation-style-language/locales/master/locales-en-US.xml"
    refreshPeriod = "168h"

[".config/zotra-cli"]
    type = "git-repo"
    url = "https://github.com/mpedramfar/zotra-cli.git"
    refreshPeriod = "168h"
    [".config/zotra-cli".pull]
        args = ["--recurse-submodules"]
    [".config/zotra-cli".clone]
        args = ["--recurse-submodules"]
