#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json


[[session]]
name = "hermes 🖥️"
path = "~"
startup_command = "ssh hermes-vm"

[[session]]
name = "hermes · diss 🔬"
path = "~"
startup_command = "ssh hermes-vm -t 'cd ~/projects/diss && exec $SHELL'"
preview_command = "ssh hermes-vm 'ls ~/projects/diss'"

[[session]]
name = "hermes · hermes 🧬"
path = "~"
startup_command = "ssh hermes-vm -t 'cd ~/.hermes && exec $SHELL'"
preview_command = "ssh hermes-vm 'ls ~/.hermes'"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
preview_command = "ls"


[[wildcard]]
pattern = "~/projects/*"
startup_command = "code ."


[[wildcard]]
pattern = "~/Arbeit/**"
startup_command = "open ."

[[wildcard]]
pattern = "~/.local/share/chezmoi/**"
