
[colors.bright]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.normal]
black = "0x3e4249"
blue = "0x6cb6eb"
cyan = "0x5dbbc1"
green = "0xa0c980"
magenta = "0xd38aea"
red = "0xec7279"
white = "0xc5cdd9"
yellow = "0xdeb974"

[colors.primary]
background = "0x2c2e34"
foreground = "0xc5cdd9"

[font]
size = 12

[font.bold]
family = "Maple Mono NF"
style = "Bold"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "Maple Mono NF"
style = "Regular"

[[keyboard.bindings]]
chars = "{"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "}"
key = 29
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = 12
mods = "Alt"

[[keyboard.bindings]]
chars = '\'
key = 27
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 50
mods = "Alt"

[[keyboard.bindings]]
chars = "~"
key = 30
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 25
mods = "Alt"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
decorations = "buttonless"

[window.padding]
x = 8
y = 4

[general]
live_config_reload = true
